### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by BASHyourbtainsout** [bluedragon1221/the-tools#2]
You do not give proper credit to the creators and finders of the proxies. Please give the creates credit, githquake network credit, proxy hub credit, glitch hub credit, and me credit for exposing you to all of the valuable resources.

**Comment by bluedragon1221** [comment]
Do you really want people to know your true identity?

**Comment by bluedragon1221** [comment]
If you want that change, do it yourself and submit a PR
